2023-09-13 11:55:39,119 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('new/post_list.html'), <traceback object at 0x0000029438FA3540>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: new/post_list.html
2023-09-13 11:55:39,121 - ERROR - "GET /news/ HTTP/1.1" 500 87853 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
2023-09-20 17:38:48,745 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'AttributeError'>, AttributeError("'function' object has no attribute '_default_manager'"), <traceback object at 0x000002AC3FDD1980>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 34, in get_queryset
    queryset = self.model._default_manager.all()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_default_manager'
2023-09-20 17:38:48,745 - ERROR - "GET /news/ HTTP/1.1" 500 87262 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
2023-09-20 17:46:23,168 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'AttributeError'>, AttributeError("'function' object has no attribute '_default_manager'"), <traceback object at 0x000002AC3FD8C1C0>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 34, in get_queryset
    queryset = self.model._default_manager.all()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_default_manager'
2023-09-20 17:46:23,168 - ERROR - "GET /news/ HTTP/1.1" 500 87262 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
2023-09-20 17:46:26,385 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'AttributeError'>, AttributeError("'function' object has no attribute '_default_manager'"), <traceback object at 0x000002AC3FEA07C0>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\views\generic\list.py", line 34, in get_queryset
    queryset = self.model._default_manager.all()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute '_default_manager'
2023-09-20 17:46:26,385 - ERROR - "GET /news/ HTTP/1.1" 500 87262 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
2023-09-20 17:46:56,405 - ERROR - Internal Server Error: /news/ - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateSyntaxError'>, TemplateSyntaxError("Invalid block tag on line 41: 'get_current_timezone'. Did you forget to register or load this tag?"), <traceback object at 0x0000025A27AA5D80>)
Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
                   ~~~~~~~~~^^^^^^^^^
KeyError: 'get_current_timezone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 1005, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 1005, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 966, in render_annotated
    return self.render(context)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loader_tags.py", line 132, in render
    compiled_parent = self.get_parent(context)
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loader_tags.py", line 129, in get_parent
    return self.find_template(parent, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loader_tags.py", line 107, in find_template
    template, origin = context.template.engine.find_template(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\engine.py", line 157, in find_template
    template = loader.get_template(name, skip=skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loaders\cached.py", line 57, in get_template
    template = super().get_template(template_name, skip)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
           ^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
           ^^^^^^^^^^^^^^
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\template\base.py", line 568, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 41: 'get_current_timezone'. Did you forget to register or load this tag?
2023-09-20 17:46:56,405 - ERROR - "GET /news/ HTTP/1.1" 500 198642 - C:\Users\Svetik\проекты\new__portal2.0\venv\Lib\site-packages\django\core\servers\basehttp.py - None
